
language = "en"
title = "WebGenerator Demo"

[dependencies]
    jquery = ["https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"]
    bootstrap = [
        "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css",
        "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    ]
    popper = ["https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"]

[components]
    [components.navbar]
        lib = "bootstrap"
        type = "logo-left-menu-right-hamburger"

        [components.navbar.options]
            templated = [ "logo", "items" ]

            [components.navbar.options.attributes]
                ID = "navbar"
                TOGGLE_ID = "navbar-toggle"

            [components.navbar.options.logo]
                template = { lib = "bootstrap", type = "_navbar_logo", out = "NAVBAR_LOGO" }
                values = { src = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/2560px-Adidas_Logo.svg.png", href = "#top" }
                [components.navbar.options.logo.defaults]
                    src = "#"
                    href = "#"
                    height = "36"

            [components.navbar.options.items]
                template = { lib = "bootstrap", type = "_navbar_item", out = "NAVBAR_ITEMS" }
                values = [
                    { active = true, text = "Home", href = "#top" },
                    { text = "Gallery", href = "#carousel" },
                    { text = "About", href = "#about" },
                    { text = "Contact", href = "#contact" },
                ]
                [components.navbar.options.items.options]
                    active = { if = "defined", set = "active", else = "" }

    [components.carousel]
        lib = "bootstrap"
        type = "arrows-and-dots"

        [components.carousel.options]
            templated = [ "items" ]

            [components.carousel.options.attributes]
                ID = "carousel"

            [components.carousel.options.items]
                template = { lib = "bootstrap", type = "_carousel_item", out = "CAROUSEL_ITEMS" }
                values = [
                    { active = true, src = "https://via.placeholder.com/1920x1080", alt = "Image 1" },
                    { src = "https://via.placeholder.com/1920x1080", alt = "Image 2" },
                    { src = "https://via.placeholder.com/1920x1080", alt = "Image 3" },
                ]
                [components.carousel.options.items.options]
                    active = { if = "defined", set = "active", else = "" }

    [components.table]
        lib = "custom"
        type = "striped-3x3"

    [components.footer]
        lib = "bootstrap"
        type = "centered"

        [components.footer.options]
            [components.footer.options.attributes]
                CONTENT_MARKUP = "&copy; %year% TheNoiselessNoise | [xyzt.cz](https://xyzt.cz)"
